version: '3.8'

services:
  n8n-mcp:
    image: ghcr.io/czlonkowski/n8n-mcp:latest
    container_name: n8n_mcp_server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - N8N_API_URL=${N8N_API_URL}
      - N8N_API_KEY=${N8N_API_KEY}
      - PROJECT_ID=${PROJECT_ID:-}
      - MCP_MODE=http
      - PORT=3000
      - LOG_LEVEL=${LOG_LEVEL:-info}
    networks:
      - n8n_mcp_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  n8n_mcp_network:
    driver: bridge
